### ISSUE TITLE
ImportError: cannot import name 'want_bytes' from 'itsdangerous'

### ISSUE THREAD

**Issue by bschley** [pallets/itsdangerous#110]
Hello Guys,
hello @davidism ,

after settings up a new flask project I hit that error:
(I marked the important part)

> flask run
>  * Serving Flask app "application" (lazy loading)
>  * Environment: development
>  * Debug mode: on
>  * Restarting with stat
>  * Debugger is active!
>  * Debugger PIN: 300-221-692
>  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
> 127.0.0.1 - - [23/Oct/2018 23:41:44] "GET / HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "c:\python37\lib\site-packages\flask\cli.py", line 325, in __call__
>     self._flush_bg_loading_exception()
>   File "c:\python37\lib\site-packages\flask\cli.py", line 313, in _flush_bg_loading_exception
>     reraise(*exc_info)
>   File "c:\python37\lib\site-packages\flask\_compat.py", line 35, in reraise
>     raise value
>   File "c:\python37\lib\site-packages\flask\cli.py", line 302, in _load_app
>     self._load_unlocked()
>   File "c:\python37\lib\site-packages\flask\cli.py", line 317, in _load_unlocked
>     self._app = rv = self.loader()
>   File "c:\python37\lib\site-packages\flask\cli.py", line 372, in load_app
>     app = locate_app(self, import_name, name)
>   File "c:\python37\lib\site-packages\flask\cli.py", line 242, in locate_app
>     '\n\n{tb}'.format(name=module_name, tb=traceback.format_exc())
> flask.cli.NoAppException: While importing "application", an ImportError was raised:
> 
> Traceback (most recent call last):
>   File "c:\python37\lib\site-packages\flask\cli.py", line 235, in locate_app
>     __import__(module_name)
>   File "C:\Users\PC\Desktop\BookLib\application.py", line 4, in <module>
>     from flask_session import Session
>   File "c:\python37\lib\site-packages\flask_session\__init__.py", line 16, in <module>
>     from .sessions import NullSessionInterface, RedisSessionInterface, \
>   File "c:\python37\lib\site-packages\flask_session\sessions.py", line 23, in <module>
>     from itsdangerous import Signer, BadSignature, want_bytes
> `ImportError: cannot import name 'want_bytes' from 'itsdangerous' (c:\python37\lib\site-packages\itsdangerous\__init__.py)`
> 127.0.0.1 - - [23/Oct/2018 23:41:44] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
> 127.0.0.1 - - [23/Oct/2018 23:41:44] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
> 127.0.0.1 - - [23/Oct/2018 23:41:44] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
> 127.0.0.1 - - [23/Oct/2018 23:41:44] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
> 127.0.0.1 - - [23/Oct/2018 23:41:44] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -

### Instant Solution (First Aid)
I fixed that issue, where I downgraded to `Version 0.24`

For other Users, who have the problem, you can do it on Windows like this: `pip3 uninstall ItsDangerous && pip3 install ItsDangerous==0.24` or of cause whith your own way to downgrade ^^

**Comment by davidism** [comment]
itsdangerous 1.1.0 was just released and contains a fix for this. Flask-Session should still be fixed so it doesn't rely on this, but it won't fail for now. You can upgrade itsdangerous and continue to use Flask-Session.
