### ISSUE TITLE
pgAdmin4 broken using itsdangerous > 2.0.0a1

### ISSUE THREAD

**Issue by hugoaboud** [pallets/itsdangerous#239]
I'm not sure this should be posted here or on the `pgAdmin4` repo.

As I was trying to setup `pgAdmin4` web server today, the initial user account setup would fail with the given traceback:
```bash
NOTE: Configuring authentication for SERVER mode.

Enter the email address and password to use for the initial pgAdmin user account:

Email address: hugoaboud@gmail.com
Password: 
Retype password:
Traceback (most recent call last):
  File "/home/aboud/iSafeWalk/pgadmin4/bin/pgadmin4", line 5, in <module>
    from pgadmin4.pgAdmin4 import main
  File "/home/aboud/iSafeWalk/pgadmin4/lib/python3.9/site-packages/pgadmin4/pgAdmin4.py", line 98, in <module>
    app = create_app()
  File "/home/aboud/iSafeWalk/pgadmin4/lib/python3.9/site-packages/pgadmin4/pgadmin/__init__.py", line 351, in create_app
    db_upgrade(app)
  File "/home/aboud/iSafeWalk/pgadmin4/lib/python3.9/site-packages/pgadmin4/pgadmin/setup/db_upgrade.py", line 25, in db_upgrade
    flask_migrate.upgrade(migration_folder)
  File "/home/aboud/iSafeWalk/pgadmin4/lib/python3.9/site-packages/flask_migrate/__init__.py", line 96, in wrapped
    f(*args, **kwargs)
  File "/home/aboud/iSafeWalk/pgadmin4/lib/python3.9/site-packages/flask_migrate/__init__.py", line 271, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/home/aboud/iSafeWalk/pgadmin4/lib/python3.9/site-packages/alembic/command.py", line 294, in upgrade
    script.run_env()
  File "/home/aboud/iSafeWalk/pgadmin4/lib/python3.9/site-packages/alembic/script/base.py", line 490, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/aboud/iSafeWalk/pgadmin4/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 97, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/aboud/iSafeWalk/pgadmin4/lib/python3.9/site-packages/alembic/util/compat.py", line 182, in load_module_py
    spec.loader.exec_module(module)
  File "/home/aboud/iSafeWalk/pgadmin4/lib/python3.9/site-packages/pgadmin4/pgadmin/setup/../../migrations/env.py", line 93, in <module>
    run_migrations_online()
  File "/home/aboud/iSafeWalk/pgadmin4/lib/python3.9/site-packages/pgadmin4/pgadmin/setup/../../migrations/env.py", line 86, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/aboud/iSafeWalk/pgadmin4/lib/python3.9/site-packages/alembic/runtime/environment.py", line 813, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/aboud/iSafeWalk/pgadmin4/lib/python3.9/site-packages/alembic/runtime/migration.py", line 561, in run_migrations
    step.migration_fn(**kw)
  File "/home/aboud/iSafeWalk/pgadmin4/lib/python3.9/site-packages/pgadmin4/migrations/versions/fdc58d9bd449_.py", line 122, in upgrade
    Security(current_app, user_datastore, register_blueprint=False)
  File "/home/aboud/iSafeWalk/pgadmin4/lib/python3.9/site-packages/flask_security/core.py", line 469, in __init__
    self._state = self.init_app(app, datastore, **kwargs)
  File "/home/aboud/iSafeWalk/pgadmin4/lib/python3.9/site-packages/flask_security/core.py", line 495, in init_app
    state = _get_state(app, self.datastore,
  File "/home/aboud/iSafeWalk/pgadmin4/lib/python3.9/site-packages/flask_security/core.py", line 334, in _get_state
    remember_token_serializer=_get_serializer(app, 'remember'),
  File "/home/aboud/iSafeWalk/pgadmin4/lib/python3.9/site-packages/flask_security/core.py", line 319, in _get_serializer
    return URLSafeTimedSerializer(secret_key=secret_key, salt=salt)
  File "/home/aboud/iSafeWalk/pgadmin4/lib/python3.9/site-packages/itsdangerous/serializer.py", line 104, in __init__
    self.secret_keys: _t.List[bytes] = _make_keys_list(secret_key)
  File "/home/aboud/iSafeWalk/pgadmin4/lib/python3.9/site-packages/itsdangerous/signer.py", line 64, in _make_keys_list
    return [want_bytes(s) for s in secret_key]

```
I tried downgrading itsdangerous version by version, and with 2.0.0a1 it worked.
Just reporting so it might be investigated (since it's a pretty fresh release) or reported to pgAdmin if it's a structural change.

Environment:

- Python version: 3.9.2
- ItsDangerous version: >2.0.0a1

**Comment by davidism** [comment]
You should report this to pgadmin. As an application, they should be pinning their dependencies, either in `setup.py`/`.cfg` or with tool such as [pip-compile](https://pypi.org/project/pip-tools/). Pinning dependencies prevents unexpected dependency upgrades and allows controlling and testing those upgrades.
