### ISSUE TITLE
Permission to generate stubs for itsdangerous in typeshed

### ISSUE THREAD

**Issue by rowillia** [pallets/itsdangerous#69]
Howdy,

I'd like to add stubs for Flask to https://github.com/python/typeshed, a repository used to store PEP 484 type signatures for the python stdlib and popular third party libraries. As per PEP 484, permission is required from the library owner before merging type signatures into typeshed - https://www.python.org/dev/peps/pep-0484/#the-typeshed-repo

Here's the corresponding typeshed issue -
python/typeshed#28

You guys covered werkzeug and Jinja in https://github.com/pallets/flask/issues/2012 but didn't mention itsdangerous 😄 

Here's the PR by the way:
https://github.com/python/typeshed/pull/537

It actually surfaced a few of what I would consider bugs with itsdangerous with `bytes` and `str` in Python 3.  For example:

```py
from itsdangerous import Signer

s = Signer('secret-key')
s.sign('hi')
```

results in:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/itsdangerous.py", line 353, in sign
    return value + want_bytes(self.sep) + self.get_signature(value)
TypeError: Can't convert 'bytes' object to str implicitly
```

And:

```py
s.verify_signature('hi', 'some_signature')
```

Results in:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/itsdangerous.py", line 362, in verify_signature
    return self.algorithm.verify_signature(key, value, sig)
  File "/usr/local/lib/python3.5/site-packages/itsdangerous.py", line 243, in verify_signature
    return constant_time_compare(sig, self.get_signature(key, value))
  File "/usr/local/lib/python3.5/site-packages/itsdangerous.py", line 268, in get_signature
    mac = hmac.new(key, msg=value, digestmod=self.digest_method)
  File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/hmac.py", line 144, in new
    return HMAC(key, msg, digestmod)
  File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/hmac.py", line 84, in __init__
    self.update(msg)
  File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/hmac.py", line 93, in update
    self.inner.update(msg)
TypeError: Unicode-objects must be encoded before hashing
```

**Comment by ThiefMaster** [comment]
I don't see any reason why there shouldn't be stubs for itsdangerous too so go for it!

**Comment by untitaker** [comment]
Ah yeah I forgot itsdangerous, go for it!

**Comment by ThiefMaster** [comment]
I think we also forgot markupsafe ;)

**Comment by untitaker** [comment]
Yes @rowillia you have permission for that too.
