### ISSUE TITLE
Installation fails with `AttributeError`

### ISSUE THREAD

**Issue by neumannrf** [pallets/itsdangerous#90]
On a clean **Fedora 26** box, the command `sudo pip3 install itsdangerous` fails with 

```Shell
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5jettonu/itsdangerous/setup.py", line 20, in <module>
        'Programming Language :: Python :: 3',
      File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib64/python3.6/distutils/command/install.py", line 557, in run
        self.run_command(cmd_name)
      File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/site-packages/setuptools/command/install_scripts.py", line 33, in run
        bs_cmd = (self.get_finalized_command('build_scripts', create=False) or
      File "/usr/lib64/python3.6/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
    AttributeError: 'NoneType' object has no attribute 'ensure_finalized'

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-5jettonu/itsdangerous/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-4m6wlda7-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-5jettonu/itsdangerous/
```

## Package versions
- `python3-devel-3.6.2-5.fc26.x86_64` 
- `pip 9.0.1 from /usr/lib/python3.6/site-packages (python 3.6)`
- `itsdangerous-0.24-py3.6`

## Reproducibility
A `Vagrantfile` is provided to help reproduce the issue. 

```Ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # You can search for boxes at https://atlas.hashicorp.com/search
  config.vm.box = "fedora/26-cloud-base"
  config.ssh.forward_agent = true

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.name = "itsdangerous"
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = "2"
  end

  config.vm.provision "shell", inline: <<-SHELL
    dnf install -y python3-devel
    pip3 install --upgrade pip
  SHELL
end
```

Simply copy the contents above to a file named `Vagrantfile`, then issue the following commands while in the same directory:
```Shell
(host) $ vagrant up
(host) $ vagrant ssh
(vm)   $ sudo pip3 install itsdangerous
```

**Comment by neumannrf** [comment]
Updating `setuptools` with `pip3 install --upgrade setuptools` prior to installing `itsdangerous` solves the error described above.
